export enum TABLE_LIST_STATUS {
  PUBLISH = 'PUBLISH',
  UNPUBLISHED = 'UNPUBLISHED',
}

export const TABLE_LIST_STATUS_MAPPER = {
  [TABLE_LIST_STATUS.PUBLISH]: '已发布',
  [TABLE_LIST_STATUS.UNPUBLISHED]: '未发布',
};
