export const ROUTE_PATH = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ANALYSIS: '/dashboard/analysis',
  WORKPLACE: '/dashboard/workplace',
  FORM: '/form',
  BASIC_FORM: '/form/basic-form',
  STEP_FORM: '/form/step-form',
  LIST: '/list',
  TABLE_LIST: '/list/table-list',
  DETAIL: '/detail',
  RESULT: '/result',
  RESULT_SUCCESS: '/result/success',
  RESULT_FAILURE: '/result/failure',
  EXCEPTION: '/exception',
  EXCEPTION403: '/exception/403',
  EXCEPTION404: '/exception/404',
  EXCEPTION500: '/exception/500',
  ACCOUNT: '/account',
};
