export const ROUTE_PATH = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ANALYSIS: '/dashboard/analysis',
  FORM: '/form',
  BASIC_FORM: '/form/basic-form',
  LIST: '/list',
  DETAIL: '/detail',
  RESULT: '/result',
  RESULT_SUCCESS: '/result/success',
  RESULT_FAILURE: '/result/failure',
  EXCEPTION: '/exception',
  EXCEPTION403: '/exception/403',
  EXCEPTION404: '/exception/404',
  EXCEPTION500: '/exception/500',
  ACCOUNT: '/account',
};
